### ISSUE TITLE
请教一下多参数问题

### ISSUE THREAD

**Issue by 0312birdzhang** [qin-yuhao/rknn-yolov5-cpp-for-py#1]
你好，非常感谢这个项目，给不擅长C++的人带来了希望👍

我的项目有多个输入，然后输入的参数都是ndarray类型的，这样在C++中要怎么写？尝试使用`py::array_t<float> input1`参数类型编译后，在python中调用发现程序退出了，也没报错信息，不知道怎么搞了，谢谢。

**Comment by 0312birdzhang** [comment]
折腾了半天，发现rknn_inputs_set出错，输入的大小是模型要求输入的一半`E RKNN: [16:01:26.651] rknn_inputs_set, param input size(393216) < model input size(786432)`，手动设置了size后报下面的错误，请问有没有遇到过这种情况？

```
E RKNN: [16:05:58.313] Meet unsupported src layout for normalize: 2
E RKNN: [16:05:58.313] rknn_inputs_set, normalize error(-1) index=0
E RKNN: [16:05:58.313] Meet unsupported src layout for normalize: 2
E RKNN: [16:05:58.313] rknn_inputs_set, normalize error(-1) index=1
```

**Comment by qin-yuhao** [comment]
你的输入是多张图片还是什么,在include
/rknnPool.hpp里in我当时设置的图片输入是640*640的
std::vector<cv::Mat> rknn_lite::interf()
{
    cv::Mat img;
    
    //cv::imwrite("letterbox.jpg", ori_img);
    // 获取图像宽高
    int img_width = ori_img.cols;
    int img_height = ori_img.rows;
    if (img_width != 640 || img_height != 640)
    ori_img = letterbox(ori_img, 640, 640);
    cv::cvtColor(ori_img, img, cv::COLOR_BGR2RGB);

**Comment by 0312birdzhang** [comment]
有图片也有其他参数，全部用`py::array_t<float>&`传参，然后用下面的函数转为cv::Mat好了。
```
cv::Mat pyArrayToMat(py::array_t<float> arr) {
    // 获取PyArray对象
    py::buffer_info buf_info = arr.request();
    int dims = buf_info.ndim;

    std::vector<int> shape(buf_info.shape.begin(), buf_info.shape.end());
    
    // 创建cv::Mat对象
    cv::Mat mat(dims, shape.data(), CV_32F, buf_info.ptr);

    // std::cout << "Matrix Dimensions: " << dims << std::endl;
    // std::cout << "Matrix Shape: [";
    // for (size_t i = 0; i < shape.size(); ++i) {
    //     std::cout << shape[i];
    //     if (i < shape.size() - 1) {
    //         std::cout << ", ";
    //     }
    // }
    // std::cout << "]" << std::endl;

    return mat.clone();  // 克隆以确保数据不被释放
}
```

发现没报错信息是因为用了1.6.0的rknn😵 不信邪不行
